# Generated by Django 5.0.4 on 2024-04-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
            ],
            options={
                'verbose_name': 'FAQ Question',
                'verbose_name_plural': 'FAQ Questions',
            },
        ),
        migrations.CreateModel(
            name='FAQQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='FAQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='faq.faqquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'FAQ Answer',
                'verbose_name_plural': 'FAQ Answers',
            },
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.faqquestioncategory', verbose_name='Category'),
        ),
    ]
