# Generated by Django 5.0.4 on 2024-04-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqquestion',
            name='category',
        ),
        migrations.RenameModel(
            old_name='FAQQuestionCategory',
            new_name='FAQCategory',
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.faqcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'FAQ Question',
                'verbose_name_plural': 'FAQ Questions',
            },
        ),
        migrations.DeleteModel(
            name='FAQAnswer',
        ),
        migrations.DeleteModel(
            name='FAQQuestion',
        ),
    ]
