# Generated by Django 5.0.4 on 2024-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_remove_faqquestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer_uz'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(verbose_name='Question_uz'),
        ),
    ]
