# Generated by Django 5.0.4 on 2024-04-24 14:10

import common.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('youtube', models.URLField(verbose_name='youtube')),
                ('telegram', models.URLField(verbose_name='telegram')),
            ],
            options={
                'verbose_name': 'Common Settings',
                'verbose_name_plural': 'Common Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, verbose_name='address')),
                ('phone_number', models.CharField(max_length=20, validators=[common.utils.validate_phone_number], verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.URLField(verbose_name='location')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='only_medias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'apng', 'avif', 'gif', 'jfif', 'pjpeg', 'pjp', 'svg', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'mkv', 'flv', 'webm', 'avchd'])], verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='File type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_text_title', models.CharField(max_length=120, verbose_name='About us title')),
                ('about_us_text', models.TextField(verbose_name='About us text')),
                ('short_text_left', models.TextField(verbose_name='Short text left')),
                ('main_title', models.CharField(max_length=120, verbose_name='title')),
                ('left_all_users_title', models.CharField(max_length=120, verbose_name='left all users title')),
                ('left_all_users', models.PositiveIntegerField()),
                ('center_all_users_title', models.CharField(max_length=120, verbose_name='center all users title')),
                ('center_all_users', models.PositiveIntegerField()),
                ('right_all_users_title', models.CharField(max_length=120, verbose_name='right all users title')),
                ('right_all_users', models.PositiveIntegerField()),
                ('header_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Header photo')),
            ],
            options={
                'verbose_name': 'Header Settings',
                'verbose_name_plural': 'Header Settings',
            },
        ),
    ]
