# Generated by Django 5.0.4 on 2024-05-06 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonsettings',
            options={'verbose_name': 'Umumiy sozlama', 'verbose_name_plural': 'Umumiy sozlamalar'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': "Media ma'lumot", 'verbose_name_plural': "Media ma'lumotlar"},
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='only_medias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'apng', 'avif', 'gif', 'jfif', 'pjpeg', 'pjp', 'svg', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'mkv', 'flv', 'webm', 'avchd'])], verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('image', 'rasm'), ('video', 'video')], max_length=10, verbose_name='Fayl turi'),
        ),
    ]
