# Generated by Django 5.0.4 on 2024-04-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaGalleryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Multimedia Gallery File',
                'verbose_name_plural': 'Multimedia Gallery Files',
            },
        ),
    ]
