# Generated by Django 5.0.4 on 2024-04-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
