# Generated by Django 5.0.4 on 2024-04-27 08:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('minutes_to_solve', models.IntegerField(default=0, verbose_name='Минуты для решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Final Test',
                'verbose_name_plural': 'Final Tests',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(verbose_name='Question')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('final_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests.finaltest', verbose_name='Final Test')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120, verbose_name='answer')),
                ('correct', models.BooleanField(default=False, verbose_name='correct')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_variants', to='tests.testquestion', verbose_name='Test Question')),
            ],
            options={
                'verbose_name': 'Test Variant',
                'verbose_name_plural': 'Test Variants',
            },
        ),
    ]
