# Generated by Django 5.0.4 on 2024-05-04 04:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_results', models.IntegerField(default=0, verbose_name='result')),
                ('incorrect_results', models.IntegerField(default=0, verbose_name='result')),
            ],
            options={
                'verbose_name': 'Final Exam Result',
                'verbose_name_plural': 'Final Exam Results',
            },
        ),
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('minutes_to_solve', models.IntegerField(default=0, verbose_name='Минуты для решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('question_count', models.IntegerField(verbose_name='Question Count')),
            ],
            options={
                'verbose_name': 'Final Test',
                'verbose_name_plural': 'Final Tests',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(verbose_name='Question')),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120, verbose_name='answer')),
                ('correct', models.BooleanField(default=False, verbose_name='correct')),
            ],
            options={
                'verbose_name': 'Test Variant',
                'verbose_name_plural': 'Test Variants',
            },
        ),
    ]
