# Generated by Django 5.0.4 on 2024-05-04 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('tests', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalexamresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='finaltest',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam', to='course.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='finalexamresult',
            name='final_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.finaltest', verbose_name='final exam'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='final_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests.finaltest', verbose_name='Final Test'),
        ),
        migrations.AddField(
            model_name='testvariant',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_variants', to='tests.testquestion', verbose_name='Test Question'),
        ),
    ]
